disableKinds = ['taxonomy', 'term']
enableEmoji = true
enableRobotsTXT = true
paginate = 10
publishDir = '../public'
title = 'Scott Smitelli'

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[minify]
  minifyOutput = true

[params]
  classicContentYears = 10
  copyrightStartYear = 2007
  myAgeBasis = 1986-03-01

  # These defaults bolster Hugo's built-in OpenGraph/social templates
  images = ['/img/mortal-damage.jpg']
  title = 'Scott Smitelli'

  [params.mathjax]
    # curl https://<...>.js | sha384sum -b | awk '{ print $1 }' | xxd -r -p | base64
    integrity = 'sha384-Xs5HL5z9qLFmNqHxxXaA0pc0PBmR1zvsdmTb85y+qHgLe7Zgh0GXJykctnLb6zlh'
    url = 'https://cdn.jsdelivr.net/npm/mathjax@4.0.0/tex-mml-chtml.min.js'

  [params.shortcode]
    audioPreferredTypes = ['audio/mpeg', 'audio/flac']
    pictureEagerMaximum = 2
    pictureFallbackTypes = ['image/jpeg', 'image/png', 'image/gif']

  [params.social]
    # I don't personally care, but somebody out there might
    twitter = '@smitelli'
